apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  keycloakAdminPassword: {{ .Values.keycloak.adminPassword }}
{{- if hasKey .Values "database"}}
  postgresPassword: {{ .Values.database.password }}
{{- end }}