apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  keycloakAdminPassword: {{ .Values.keycloak.adminPassword | b64enc }}
  postgresPassword: {{ .Values.database.password | b64enc }}