apiVersion: v2
name: zalf-nextcloud
description: >-
  A ZALF-specific Helm chart for nextcloud. Beware to adapt the template 'config.yaml' in case
  there are changes in the dependency chart.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

dependencies:
  - name: nextcloud
    version: 4.6.4
    repository: https://nextcloud.github.io/helm/
  - name: collabora-online
    version: 1.1.11
    repository: https://collaboraonline.github.io/online/
    condition: collabora-online.enabled
  - name: fairagro-onlyoffice
    version: 0.1.0
    condition: fairagro-onlyoffice.enabled
