apiVersion: ENC[AES256_GCM,data:gvw=,iv:xkjfdzgcc6X7x6t46E6KYlPVkZu/OZrIDIUGZfayn4A=,tag:FbERL7kZ0PvPi0dZ75XfYA==,type:str]
clusters:
    - cluster:
        certificate-authority-data: ENC[AES256_GCM,data:+T46lq1WMd6syWUzTf74jcAOri2isU9JwaWHCrEDq9AipjWW/3JqafUPNVxyOfOs3l6VnJTgeG8WjsxHQiCKCJq9P28/WL8sYkWAXuwZXw2H+q8BrfRFBrazNM68ftU5PAUdOfAHBXaxycHODUmm28iu0DkKVx+2w8oNfe9PBSseh9Txv0OgPvP5NBniFePrRs36V8U6eFiL6pzBcfhcQ/ecqnME5DXlX+zawxtUvHXxEcJpbAHfTziAV2nxSoaHKCr9xJEb7OwNOzrr2q1DV+2oN4OoLRE1oyXO2OsBl0pjI+uDTA0DKfjgVvdNGi8YauPyZ2pnyf3I4UnKg+kS57ECdrV6Xq2CCAwnJQagxO1UeZK6YUyTUG39EpyonhjLANuR7c1NbHhe65dTb4tFspZtMFrwRi3gSNp0xLg7oXCZDKnnln6vX0VT8F4GZRjAv3mxrI7F2GBB/VnZ21w2yiJinjGNdOO/0i8vRaQx5DYMk7daz3bLnOIUdjBplyvVa/jgnnnTUTdinHKONPq1T3XheIVA7GCkh+FZSz2y8tZTUYFoFT98LJ5fIci9FKbUWU1lhsJ827E8CGcphAM7Cjozg1cZ24w37vehV4xiEFsdxKL8Lpm99rZXky2APNT3YafA0GIBtErudqBiu2ZCyc2Xbxq2KtmCAUxknGngVbVPlh1Yr8kWqRe+GvGePXHsPREhFFouNCPWo79B4SxrlFTfFD2bPJFRz1ZxdADl+c7yPutGjt0EIghqIJq5PQvDID8ISMJBGotR7deuc1fdIdZJtmW0lKSLKY1s6k4ZW+/p/dutmwc0jakpEJxPxq+EAZbVSRAIhi2yZGhWnYfmWvP6P01oOob62EcJ44sxj62MnmtiIVgSP0iIY6eC3holfR8QZ3osZOSXNxozIrnwWJZ+WeNHPVziVSmtSRzNc0ML9N3ABwHuztPYdqq0dSbFXOp36Efusi4m8+AgsgGBUGGATouQfZo5ykpUbu9ZxCfAmlif29F0n/IfJ/JG4jUUblED+1VZfc9llOudxxJ6AbBYAW4UOSqGW4fxBOdj1dbDdEm41V+liNs4IHWWjzhx6No78uqZUJIiHK1XSgXBKjWVD+72xjUdCMcgyfIeGmUUaFBt+VH4yHq8eHwcuw18r+5F4Pi2lPyxsccKGtL+0SF0gc1c5RuLDMAAPMrJ/rMhEehFbVZIuzuABUot3JnShqHni2JDwtAYkxP2pEP4kepkqKJPAq4MN5RhI3kxoDu/UgbQykTLkmiPOe3k3ZXFiVeMbG7OWr2exJF50LhbI8gogui7SP3QdJAgKAXljpQOWQYpkv3VrFyb62WlF1yuIx4mdlwIvAkJMnvttGvqoz3yWIJ7QWXn1Q4/WuAH8KP+JNBk2WWSlCkgCzF64UqInDdEbGZEakRv6pNus/0dDojQypLlvFqknRCOYQf0coBPJ0PtDNjFlHJw3lG7PKSLFgYKdJAbuHQgOr+t/W3oRAjJ+pp4YHZM/qy2lcs1wX+2waAWAOPWxNP7F4rqq8n/zRcfmY4f8FSoCV568AfF3DbT+jT1ml4Pi37/mqwMnl3du1Q+FrqlHpySB1NZywtsol4f2tzDcv+gEMU4f1Lq1+JsEuiYGdqW5dtY830UHmh3o3kk4dZd3HcyiBTSoZZ7Y85B/QjCQ9AIO0zgVUIRKtLTn31iVzsgaSfjFuMR/Kgft1oZOBzaO3IPd2UXJrDL550N5uK7zzZVPcype1AYvF/MTJ7aRy3IaCHPyPizg9M9+D9/Utzqnzxs0Z6z2mIumtDCX0EwH+UC7JR4ixsDU8nh9SZqpE+SrjSLSul8fOHw+Hhgkhxpp6E/8h0Gc2XAYt3sYCT05qlApplIL03583qWE4hROu/deiIepijfKZPAIDxE1kyPWKALjj97aZR5EfOkcj4Z5ERYTzym2yrRo1fCt77bKYF4r6Pgw8vzpngdTPG1,iv:M3K2Qu2Yq6lsFxiFDMgAHarmFJL+9wndZW2d1VkxrJE=,tag:4rQNoPvN+rNCCyyJiqZuhA==,type:str]
        server: ENC[AES256_GCM,data:Sz8o8E+oO6H7kmp1CoA+et8bDm+Zsecl,iv:2utJ6c2U/87bXGwrZmaM6nMdt3oruW8MAxwClsAWY+E=,tag:1fRgrZjG3jriu8M5KNRo2A==,type:str]
      name: ENC[AES256_GCM,data:nORDex/LPRKqLnOjph0=,iv:2WCcGyrP1CLoECWPQhPoBIXO0vIjyx+ASBj9D/HzTfE=,tag:T5vIRAJa0iENT4yGlfhjMw==,type:str]
contexts:
    - context:
        cluster: ENC[AES256_GCM,data:tOKNkUq6axy0zFHoxS4=,iv:kM/CYMKFYmrx608aTKme4jDGQ75eErFtKjOXcZjg6/c=,tag:5NnnpeOmy/nTHuMBebhfLA==,type:str]
        namespace: ENC[AES256_GCM,data:7+4rbBrrg5qdIM9SEivJZKA=,iv:gjzvWbLyaM7r2AIgZWJpng20c+toZnqllHe/IxelsHw=,tag:svdf3mOtO9dyb2K9l/c+WQ==,type:str]
        user: ENC[AES256_GCM,data:uAsk9gqffS2CdMlpi5I=,iv:V+G57e7tCCyf3/4ouK25fwezR5HyNGWlXF74Y8MuJKs=,tag:/nMQHicv/2kJTfphQq5seQ==,type:str]
      name: ENC[AES256_GCM,data:IKVxiBcmr5DCzOom1FIXvZrkSQ/NAGMs,iv:issF2lVin/O5uFvRABMDXnHFGJcLe8jq2K5JU/+f7mQ=,tag:S1HxnRMd52nB5ykMCB6fKA==,type:str]
    - context:
        cluster: ENC[AES256_GCM,data:tOKNkUq6axy0zFHoxS4=,iv:kM/CYMKFYmrx608aTKme4jDGQ75eErFtKjOXcZjg6/c=,tag:5NnnpeOmy/nTHuMBebhfLA==,type:str]
        namespace: ENC[AES256_GCM,data:lGUN7HolN0PCmJbSEDHw6uHY,iv:FinjbUjHYAqpQ8Eps+7Ef0w8wzbyxWNMFVMltZJnfV0=,tag:Zx9oqDOjgo6g8hdkra/1sQ==,type:str]
        user: ENC[AES256_GCM,data:uAsk9gqffS2CdMlpi5I=,iv:V+G57e7tCCyf3/4ouK25fwezR5HyNGWlXF74Y8MuJKs=,tag:/nMQHicv/2kJTfphQq5seQ==,type:str]
      name: ENC[AES256_GCM,data:1FdeNQjTgza6xW/k7bS92jr1jf9D/Su3Rw==,iv:OnpjiEkN1qlBK+ONgcPi86uA/ORf/VwJYzMjAgiX3tc=,tag:HQcYiISgMsHxydj2zKdPHg==,type:str]
current-context: ENC[AES256_GCM,data:VGzoljYQ5LLVXff0dAvrsXik3MiMcQVooQ==,iv:uWKZFlOAWY2idhobLMyriI4NoK9O9/lhiECKw0JAsd0=,tag:FlHPEPZaguIf0AfE4yb8tA==,type:str]
kind: ENC[AES256_GCM,data:nwdBaBQj,iv:3fFvlqbY6yCnIeZz/fjqHPLK68GBjl0UOeEzxu64Nco=,tag:D77yhCoSfv4Xy9ZtEqUd7Q==,type:str]
preferences: {}
users:
    - name: ENC[AES256_GCM,data:hAXcFiR5oktjMrLHR5Y=,iv:DKLGFN/X2F6sGiDGaFHmorEyI4y6H1iOzl5/Wb6udm8=,tag:6Gsbkj6hXaeNmrDejwQz3Q==,type:str]
      user:
        client-certificate-data: ENC[AES256_GCM,data:oJmt02bhDzlNdjhwTFPcresZNs54SPs6qHjKEazyQ/624FHqWBwC6o/77Hg76I15V7quUGQvcWlW0H6X46H0Bil4OgVOb4QtghAqalpC29nSef9wLNwNv88hMhVZ7RtyZjRSEBv6ze7IDGT5ip1p9PQbA8aDJ9b5RkrRMpu+8ytBNNynMxsfL7Jpp0r9V7YpmB6jsKMubbuR1BlSJk5Wc1qRXqqgdqyz6dxoUOlJfqomUVzYou0eWmLylj6Got6T15TdpZaIl3dWubPXp7IvLONcVN814eKbVh9hGR2uvGHjTIWZ8Rp7YqVcJ/UhFVn+8u6scADmCvbbAeSJe1zGP4cphUiaui8JluI/H6wwmItwhQ1kvt/ucCqEd16HyHMGEJUqKGM4Oi5gxc10+n6NkHm4dn9VwvqrFcsIoc8Y2alfcVWDfSv25jnaPfmtHS9uS1FwwAvvcsfcBdhnol2ewsZB6eCbNlQ1DkwjY7NffjL05z6Hq1u7OSZ5AtM0UJCK7ndW1vfB4u2noguW74JIKPiyfUHe11NqoO6gLIQoJf3PMjWRT+CPDlcG6PyPgtlT3FFL+W9OUf3tJAYry2CIIrUihvqpvHBjU8WMY2i422mu0gu1tlf1StPpgecZY3FxxtVw5JmqGaw3HX83xHOUgNzx6UBf+8FjT6Sm4Y9ogcHGW622m7pMIld6XFJNNDQ6ad/CXmv5xF5KRIrlop1Mnq4bHYCnCIZsM+LtPcDmTu0N4lxjzq8i/2l6SpHrLVecZXYSQJXhE08oopqZ5/fBgZ0DRXAmtGgsFiGQRD3sNV653FTZ9JvX9WzqS9xcdFiRv1dMntuVoG1mWeSoKfSdGT4zTTxiDytTzJfRj4qCz+okpAoUB+c+SOSITyVtwhIsuaGBlAB/RNOYynQfGK7L7kUGdH4wa/061QX1CNRLh6xR5Z37f/b7VB81Uabr5O5DOZ5do+C9k9EbHgzX/UWBkBilcA5EuCW+5qrzsYic6EzL8ep7RxexG7VQEiSwCCyBypuJwZ7nj0znKm/VhT7B9lNZYMpTxxziyUOK+nAl3ropkl8GWZ/08FCrwctlXQF1mxWyuCwTQAKxBncmUKkjvTL0bA7FoFL0MvspQpKET8mPU1qhGH44roDEEnJRmG0geFv6qLeOXNKc+W777VvUCAI9yALRjoknX+BNJKdS5cM7byQWmOm3GhFQLaD+LJLQIyY/RfFrvuChDSY16hK/Q+4Xaa1+Ugjf7RHkHbM8giSpd0s0NBXMA8Y2ued02FcLohBqoxByA7oqct0vfxz1/mQVIZE/LAYQoBw0vV2uXb5RWm3jg3rBt5u/hMQJW3RSXgexvW4RWOz5wib7wWh0en7bvz/iHb4TN17nvYbWg+67DfPm,iv:wdPPG1uOHZnKexXkZVG0SK2fJIpbYFlluczJvGcodww=,tag:dbiG5VMHBUs/UiRywly8Rw==,type:str]
        client-key-data: ENC[AES256_GCM,data:dm37BO2G6GUe0GAu5VUN9cBX5CnoaP9SCRR4L5ydMXFtWxfbzH6I2N4n/T75IwT4SxRhoUP7z1koM8/RQ/xEgWyiCb6dRwMjc7wDmg5EUvg/nKEXARZ04Sgulnr21rFRverNzP9oP+GCSW/U/6LCJHhhILo7mvv1oT3cJcEIpvNZRmyHhinXiGQqJaF12256WLGJwhbY5z94a9ere7ieoQ==,iv:rIkurb2NXJHZ4P3yDAKbTK+OL3Tv2Gw5ukalIb4bEzg=,tag:Fss/iMJsJUC28hTgGmf5Aw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442vmk8fl5nxrejuj0g6a63cqdw7q7ufvnxuqf3wcsnetgmv2phsl8eufu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaXdiTkFTVS9PNmhIVTJq
            b3V3VlJLNTBxWmtPaVpjS096aXhxa0pKTHo0Ckc4SUFnWmhvSkRFVjdHUWV0Qm10
            Q04ydjVjWmhxeXc5ZEZmdjVhb1lBRVkKLS0tIDFxempBcnMvamxvVmw5NzlTSDh5
            NExxcGVYTUd6Ri9aMTkvdnJSNGtqdUEKImnJKvL/E4XbLNgiSnWJ11xel38gFw19
            jjyIFVBotyWHiZ1lYj60/0uG0xoUottUqbjH/yg9Bn/cDzqrpDonpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-13T14:09:31Z"
    mac: ENC[AES256_GCM,data:BxaVO8YbsUXVC39/ct/NbOqioMs2falB/HVw8Er6NXyjdjYpVfO0f81ZkG5nAEnVEiMPh/87web2Q1WpOK2SJoFsGIC3b99ykVxHGg8+JotbxJkBy8O6mH6K+LIEoLzNZJC1gTxcF1oiXOQPysuMjgBsMEuGoARxN3w7t4qvnzg=,iv:qZvLjlxOduvgKHCm3jBX66BrLaKfN33vB3+vySeE4O4=,tag:LsRLwreAkzlPUY+DotepcA==,type:str]
    pgp:
        - created_at: "2024-03-13T13:45:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3FtoE4fF3lxAQ//fFOjwTt8fbxBVVBqEgkuHlpjolQWrdmQvck/on16CU6J
            t8IWHMSv4759+4wkLT2NagPWe4EewXv4x1v7K7PXtLCYtLwxvnq6mclt6aJHloVc
            EfbwgsO97/OOz1JVXL/TMGo1eymPdicZZW9epjzKjONmAiPZiMK0wlGQeissLgiJ
            uQXDDPiR7mu2FvHBcQIOwqfkF6djdL5CCKijpavR6Bytjd4KDYYMdfvqlIVl9M6d
            3tBeiaRTZKh3LVrFflyHfODT+uwS78O7x5RU6ZrAFFX/0LisDDj1vH43E15Xrpjj
            PN0yoPvcF+Nzw5aPn5JI/KYDolG/PQarj1uwTVSNPyqdfLiXlUBDA5AWwTzwFVDW
            mVmIwLouzbOSG/5mv8VHd3hXiE+qvYxducX90GLdbBP4m+ddFuw/qrPGr5NoHJKI
            KZr1sSVLGXF1vjvztmJTUL1hSEkn3zRLTTIsYNe/ucJBG4CtD2U9APRUxK96NYdO
            YqdynBvck1Y3ogzIDvtJwAVQ0P6RSDbwXjKwr/HEU0ACoVH06I36ZFwehSLZ29wB
            2FZ8WyknPyvY5gg3/C1ZaBju3o30mWzmQDxXMPRqYxfl9DqlVZxvBgWFaw5bSSFZ
            FU+gNkLH/biX3p2dT9DGWOH2/NLVYF9UNDS8aL268QFLdPY7C6dJKhcso1efNaPS
            XgFhjtU3urgDg3QM6K953jwEhW5MEp+nAASPR0NTAWnbozeQL5E8Xz7pa9AcK+tb
            ec+DY3G6CnlCbtHhsNxl9Wc3zMeVwqDG9AD0zVTPp6jXY8nQbVA8oSbTnB3SfPY=
            =uM0Q
            -----END PGP MESSAGE-----
          fp: DC8231FEA934DB14D402E72D3B6555ADB3910EAE
        - created_at: "2024-03-13T13:45:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMAzD2NYmhq+4pAQwAmCXFnrgz/zRd4MSqN5dFUnY5lTM2bgcnXLg4fU3buhj0
            IT/CLnaYOaWRQ0b9Uf85gpYOp+xSXKqFbLOxOVoLBj0GNfE9ZtoarwNwXTx7a99b
            tf2/dTG4JtiJ+rVVYJMC9YsMrIkAZfiLMAxT4lurgsk+rZdWc9kQ0ilEXxdxbKRr
            pevCCPRfjO1b22PpnT4IVZCbT6F5ft83KpcTkkRrmSpOgGJmaOiBQ4ob11pvM2Ww
            H/0ejv1PseW4XWlJLLLsOMO3xeoQVNKze8fDiQYp/LBVBGYokJlFYuEkbwL7/bKE
            FlGWu1IIMeRiVP5LJQP7geY3aLt7+vIw6bNpXWXlwKn5plc4Ri2YWwhAo8g+E5f8
            vR8bT7g4OQyU567FEWL7mVsDnHuWurGm5NxUXMCVwku/nCufCZgRCYVEbFLzbo1R
            clL/bCaGGJh7FTnA7mWseGlGQKRXUl1/X4asqBL5m9Kq9CXgHG3f/x6zrvcLVS/r
            FivgtcmHOiqm6MMBGAXy0l4BFp3JaSf4pGcJPp3e6M23G4aLA+thzzQHH0143urd
            eW5FE+QY8vmoTkmnALoF5IfUc6ztDDMBoNdsbLjBMwplQqRrQDXKewnqljEi/7ay
            2G97L7VWirjJTNSKXHBl
            =ll0s
            -----END PGP MESSAGE-----
          fp: 74CCFCF1D43B0DB742CC2602A103D9F46B9D2E02
        - created_at: "2024-03-13T13:45:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D5jdJleHfCY0SAQdAFBKHY30Sf6sH0CMQIXYV0sro9Gi2LxYQmIdIbG77B0Mw
            grEFrI7bPKaufDPFMLQPsOSWP2ySzo8vjtzdPyUfdhr0gTm3okdLjv/YXPuPVsPY
            0l4B7sUaP3y2eyU1jsZPNhpQwp+fDck5PdFl7GdWly2DlkNYSi/YSVODJSz9gYDi
            iwLxaeYNJhayTUicNj065wwMoAi8HY5Mug+OC2MyA/CESOvnHrWoJorwLTSwrcH1
            =2eMN
            -----END PGP MESSAGE-----
          fp: CC7B10CE8D78010ABB043F8DB1C462E90012ECFE
        - created_at: "2024-03-13T13:45:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWYQsjg0n8MQSAQdAkEicP8hV3SQPl3UizuULpUVG76lceINxBdtWAbQRkUsw
            H+bokx+rNIz7bGCC0LS+71Bdessj3+ZUT7JIhOVS0DOg0opUI2ykkGCGUN1WfBmq
            0l4Bm/Gn8qqgKNMX04jsBQ6TQ8SlzOIRz2yx7qrgqHKzwkng4qbGoeE2o/ZFsJpV
            yayV5Da4BNqqJbJ1CHvsggkvxrLsww6vq8gHJO5oai5BD/1cU/dFQaH7xEGFuaE8
            =zj1d
            -----END PGP MESSAGE-----
          fp: 22E1B5B742AA7D66DB7FA859E5DB947DBEA3A7F4
    unencrypted_suffix: _unencrypted
    version: 3.8.1
