apiVersion: ENC[AES256_GCM,data:gvw=,iv:xkjfdzgcc6X7x6t46E6KYlPVkZu/OZrIDIUGZfayn4A=,tag:FbERL7kZ0PvPi0dZ75XfYA==,type:str]
clusters:
    - cluster:
        certificate-authority-data: ENC[AES256_GCM,data:+T46lq1WMd6syWUzTf74jcAOri2isU9JwaWHCrEDq9AipjWW/3JqafUPNVxyOfOs3l6VnJTgeG8WjsxHQiCKCJq9P28/WL8sYkWAXuwZXw2H+q8BrfRFBrazNM68ftU5PAUdOfAHBXaxycHODUmm28iu0DkKVx+2w8oNfe9PBSseh9Txv0OgPvP5NBniFePrRs36V8U6eFiL6pzBcfhcQ/ecqnME5DXlX+zawxtUvHXxEcJpbAHfTziAV2nxSoaHKCr9xJEb7OwNOzrr2q1DV+2oN4OoLRE1oyXO2OsBl0pjI+uDTA0DKfjgVvdNGi8YauPyZ2pnyf3I4UnKg+kS57ECdrV6Xq2CCAwnJQagxO1UeZK6YUyTUG39EpyonhjLANuR7c1NbHhe65dTb4tFspZtMFrwRi3gSNp0xLg7oXCZDKnnln6vX0VT8F4GZRjAv3mxrI7F2GBB/VnZ21w2yiJinjGNdOO/0i8vRaQx5DYMk7daz3bLnOIUdjBplyvVa/jgnnnTUTdinHKONPq1T3XheIVA7GCkh+FZSz2y8tZTUYFoFT98LJ5fIci9FKbUWU1lhsJ827E8CGcphAM7Cjozg1cZ24w37vehV4xiEFsdxKL8Lpm99rZXky2APNT3YafA0GIBtErudqBiu2ZCyc2Xbxq2KtmCAUxknGngVbVPlh1Yr8kWqRe+GvGePXHsPREhFFouNCPWo79B4SxrlFTfFD2bPJFRz1ZxdADl+c7yPutGjt0EIghqIJq5PQvDID8ISMJBGotR7deuc1fdIdZJtmW0lKSLKY1s6k4ZW+/p/dutmwc0jakpEJxPxq+EAZbVSRAIhi2yZGhWnYfmWvP6P01oOob62EcJ44sxj62MnmtiIVgSP0iIY6eC3holfR8QZ3osZOSXNxozIrnwWJZ+WeNHPVziVSmtSRzNc0ML9N3ABwHuztPYdqq0dSbFXOp36Efusi4m8+AgsgGBUGGATouQfZo5ykpUbu9ZxCfAmlif29F0n/IfJ/JG4jUUblED+1VZfc9llOudxxJ6AbBYAW4UOSqGW4fxBOdj1dbDdEm41V+liNs4IHWWjzhx6No78uqZUJIiHK1XSgXBKjWVD+72xjUdCMcgyfIeGmUUaFBt+VH4yHq8eHwcuw18r+5F4Pi2lPyxsccKGtL+0SF0gc1c5RuLDMAAPMrJ/rMhEehFbVZIuzuABUot3JnShqHni2JDwtAYkxP2pEP4kepkqKJPAq4MN5RhI3kxoDu/UgbQykTLkmiPOe3k3ZXFiVeMbG7OWr2exJF50LhbI8gogui7SP3QdJAgKAXljpQOWQYpkv3VrFyb62WlF1yuIx4mdlwIvAkJMnvttGvqoz3yWIJ7QWXn1Q4/WuAH8KP+JNBk2WWSlCkgCzF64UqInDdEbGZEakRv6pNus/0dDojQypLlvFqknRCOYQf0coBPJ0PtDNjFlHJw3lG7PKSLFgYKdJAbuHQgOr+t/W3oRAjJ+pp4YHZM/qy2lcs1wX+2waAWAOPWxNP7F4rqq8n/zRcfmY4f8FSoCV568AfF3DbT+jT1ml4Pi37/mqwMnl3du1Q+FrqlHpySB1NZywtsol4f2tzDcv+gEMU4f1Lq1+JsEuiYGdqW5dtY830UHmh3o3kk4dZd3HcyiBTSoZZ7Y85B/QjCQ9AIO0zgVUIRKtLTn31iVzsgaSfjFuMR/Kgft1oZOBzaO3IPd2UXJrDL550N5uK7zzZVPcype1AYvF/MTJ7aRy3IaCHPyPizg9M9+D9/Utzqnzxs0Z6z2mIumtDCX0EwH+UC7JR4ixsDU8nh9SZqpE+SrjSLSul8fOHw+Hhgkhxpp6E/8h0Gc2XAYt3sYCT05qlApplIL03583qWE4hROu/deiIepijfKZPAIDxE1kyPWKALjj97aZR5EfOkcj4Z5ERYTzym2yrRo1fCt77bKYF4r6Pgw8vzpngdTPG1,iv:M3K2Qu2Yq6lsFxiFDMgAHarmFJL+9wndZW2d1VkxrJE=,tag:4rQNoPvN+rNCCyyJiqZuhA==,type:str]
        server: ENC[AES256_GCM,data:Sz8o8E+oO6H7kmp1CoA+et8bDm+Zsecl,iv:2utJ6c2U/87bXGwrZmaM6nMdt3oruW8MAxwClsAWY+E=,tag:1fRgrZjG3jriu8M5KNRo2A==,type:str]
      name: ENC[AES256_GCM,data:nORDex/LPRKqLnOjph0=,iv:2WCcGyrP1CLoECWPQhPoBIXO0vIjyx+ASBj9D/HzTfE=,tag:T5vIRAJa0iENT4yGlfhjMw==,type:str]
contexts:
    - context:
        cluster: ENC[AES256_GCM,data:tOKNkUq6axy0zFHoxS4=,iv:kM/CYMKFYmrx608aTKme4jDGQ75eErFtKjOXcZjg6/c=,tag:5NnnpeOmy/nTHuMBebhfLA==,type:str]
        namespace: ENC[AES256_GCM,data:HlLuHc2Kce4iDrxrOdAyhvWEiThm,iv:7b51yFHPO4+vQdyen8KwChV0eX72yWRmfX3keL/VxzQ=,tag:9WoqATV6Hhif4KsDAg7g9A==,type:str]
        user: ENC[AES256_GCM,data:uAsk9gqffS2CdMlpi5I=,iv:V+G57e7tCCyf3/4ouK25fwezR5HyNGWlXF74Y8MuJKs=,tag:/nMQHicv/2kJTfphQq5seQ==,type:str]
      name: ENC[AES256_GCM,data:dEP9AfhhTDufE3zeW96PMmyXd2rV9NHV92Mgzg==,iv:gH1qBTDwXQAm8Z+qQqmPzNGLd2CS7pzd7kCPJMli3HY=,tag:eIMi3Y5tEqOwAX75tInqww==,type:str]
    - context:
        cluster: ENC[AES256_GCM,data:tOKNkUq6axy0zFHoxS4=,iv:kM/CYMKFYmrx608aTKme4jDGQ75eErFtKjOXcZjg6/c=,tag:5NnnpeOmy/nTHuMBebhfLA==,type:str]
        namespace: ENC[AES256_GCM,data:tdl8/dRzXk0f6xQmZ6eYnQ==,iv:TpzeEdpuizNZAejlHVvDYNO+gxiGBp6MBTrma6wijjY=,tag:OLeS6PfvG3eiC1Eg6c35FA==,type:str]
        user: ENC[AES256_GCM,data:uAsk9gqffS2CdMlpi5I=,iv:V+G57e7tCCyf3/4ouK25fwezR5HyNGWlXF74Y8MuJKs=,tag:/nMQHicv/2kJTfphQq5seQ==,type:str]
      name: ENC[AES256_GCM,data:+J6t6u6LhMIVMCvzMIt/xSQaVaRNV/c=,iv:orhY2f+YYBLylav1evS9JJFGHdW7pLEROTM2/TKdZs4=,tag:CHbTJtMkxqGUcvjCVIrnYg==,type:str]
    - context:
        cluster: ENC[AES256_GCM,data:tOKNkUq6axy0zFHoxS4=,iv:kM/CYMKFYmrx608aTKme4jDGQ75eErFtKjOXcZjg6/c=,tag:5NnnpeOmy/nTHuMBebhfLA==,type:str]
        namespace: ENC[AES256_GCM,data:lGUN7HolN0PCmJbSEDHw6uHY,iv:FinjbUjHYAqpQ8Eps+7Ef0w8wzbyxWNMFVMltZJnfV0=,tag:Zx9oqDOjgo6g8hdkra/1sQ==,type:str]
        user: ENC[AES256_GCM,data:uAsk9gqffS2CdMlpi5I=,iv:V+G57e7tCCyf3/4ouK25fwezR5HyNGWlXF74Y8MuJKs=,tag:/nMQHicv/2kJTfphQq5seQ==,type:str]
      name: ENC[AES256_GCM,data:1FdeNQjTgza6xW/k7bS92jr1jf9D/Su3Rw==,iv:OnpjiEkN1qlBK+ONgcPi86uA/ORf/VwJYzMjAgiX3tc=,tag:HQcYiISgMsHxydj2zKdPHg==,type:str]
    - context:
        cluster: ENC[AES256_GCM,data:tOKNkUq6axy0zFHoxS4=,iv:kM/CYMKFYmrx608aTKme4jDGQ75eErFtKjOXcZjg6/c=,tag:5NnnpeOmy/nTHuMBebhfLA==,type:str]
        namespace: ENC[AES256_GCM,data:ZfvEeVNHT6dp1TjsdCYG,iv:sHM0SFRnQrzWycWvHLKWgwczFQLuVTMYV1yYcCWMeAk=,tag:pO+yx70LvTQ9DLg53GWY8Q==,type:str]
        user: ENC[AES256_GCM,data:uAsk9gqffS2CdMlpi5I=,iv:V+G57e7tCCyf3/4ouK25fwezR5HyNGWlXF74Y8MuJKs=,tag:/nMQHicv/2kJTfphQq5seQ==,type:str]
      name: ENC[AES256_GCM,data:1VddZIuiqirtdQah4mqAa91jAZwRZw==,iv:/oWTfNOFfhnMjcwypU4CL0ALaRC6udCcf012hpGBoFM=,tag:AM/UKMlNQbjDIn7Mp2ZaJA==,type:str]
    - context:
        cluster: ENC[AES256_GCM,data:tOKNkUq6axy0zFHoxS4=,iv:kM/CYMKFYmrx608aTKme4jDGQ75eErFtKjOXcZjg6/c=,tag:5NnnpeOmy/nTHuMBebhfLA==,type:str]
        namespace: ENC[AES256_GCM,data:Se6uhZg+5z7V46EdcYdy,iv:MyVNTIsfChz4l3s14D0CmS5nmkEO17cdaqmOEuVWVxg=,tag:YJEOO46zzysOG3YuBo81Rg==,type:str]
        user: ENC[AES256_GCM,data:uAsk9gqffS2CdMlpi5I=,iv:V+G57e7tCCyf3/4ouK25fwezR5HyNGWlXF74Y8MuJKs=,tag:/nMQHicv/2kJTfphQq5seQ==,type:str]
      name: ENC[AES256_GCM,data:lNVZrKwG2VZmaFDZQfx5qXbE+wW5vQ==,iv:+0XB9uida1u7Bo+s0bdGsk46CrJK5tWLTmPAwyUM81Y=,tag:j8YvNDC98Zzgfiy0llFwyw==,type:str]
current-context: ENC[AES256_GCM,data:48wokWG1yNM7b6Qm+l2RIEyDAdYKVqeNplOYBw==,iv:lDvm+hLVfykYnRCxSQUkkMj0FBxQBG15hTgKzJDXggU=,tag:6CC1mIoUeSjcxlNOn3QHNQ==,type:str]
kind: ENC[AES256_GCM,data:nwdBaBQj,iv:3fFvlqbY6yCnIeZz/fjqHPLK68GBjl0UOeEzxu64Nco=,tag:D77yhCoSfv4Xy9ZtEqUd7Q==,type:str]
preferences: {}
users:
    - name: ENC[AES256_GCM,data:hAXcFiR5oktjMrLHR5Y=,iv:DKLGFN/X2F6sGiDGaFHmorEyI4y6H1iOzl5/Wb6udm8=,tag:6Gsbkj6hXaeNmrDejwQz3Q==,type:str]
      user:
        client-certificate-data: ENC[AES256_GCM,data:FAIAQ8Z0TPlGZm6gILBO4FJmjuMmfIRgbgI1Cw/h1s9VCBBoh89/TxmyVg3UhhdNqP53TCnhFHuEB+yjSbXMH2Kx3JVIiCeb9xb8IbihbMjMvlo/eiHIvqvjDrVNiHto+TYHM6Xncke4hfMbqED+TnQQtUTVrT8hep20gl8Y5GrkikxU0Nuti1et5Rb1P6vB2WmzVBcgpr7fopZxeAqTYKM2e7FprXi2yt5Odc9TBe5dXiOj3CZgbJM67fsdQJ4dHCkzWdvYCG7BHJEwim+zE7/2E+WQAmiNDsWs+LXRlSEK1EWxZviBMg7yK+1xxBYq32aUflchor1usLdANomZFtrZKICbBqdttz9rwsQBWq5zhsIvU18luxBFw/2sSJN+SF0oZE7FxhyMCPyblVmDw9syVYFXMAYQZDh5n/bLmIEa9mDKLLvDiFRDbQBGx+b/HHKC6qZZisPziBj9XEpJsg30YsJyHPdeq7Jw0pmmFHpKSCsAlLrxoySJZNCEKkAR6s4h5QAM4qhGwDcSXuMWCtAN10cbWBSzrX0MYPp3VeeLCb0CNyt4R9Wcy5TLMnPP1sNtOr9APTF1li72nl/iQTzVGQuW1ZREYw0VnCYW2Tb5b0dicPz0+GO5GzuZ8qkVX1ugu/SMvKwbxO2nofmICWGgVdg5RtdvNrHNgDNaH/LZqqMsHqVwdp25kMiTCo2zlS777m6zDTDsQRx2LFUCHK4SWF10JbrFYqsxV18bTOJWOd8HZ5QT3qEZjBpFS9PXNGCm+f/Lbhd9JTQXTqLkbJPW6cD8L372o7P1n26QduQnGiaOWZS7V4W6j66ObP3lrIq+YxxwV6to5iXBgzwx47HOpdIXF4WCRcM3qPcv5BdqgZlAssJOITDRygvhaag5yl+fwbiJKUDC/0yAuSKaJScKAuZjqAxKezx78NxZHuAedBrSmoMG6Ch9uAkRVbl6T7SJLAZcYcsLb7rlGeqGQp9wZPEyu/b8BP/nvgElJGl8cnMe5sp6U0VeIu3oyp+WBF4aAdeWxkXEeUX9rtVqoEzQ1ql9bO8Baa1/yoZ07xQH/jJbb5dqgGc4fYuX/XQDeXVSaHrADr5QqYwkWG490to6dngMZhio9PB9tr+Rj5ZlWzSeYT+weLKuqzgoh8zHCSfgdfY4nwXURG7kBsqrjxm04d3KS9bpfFlmrLiVUkzq1b7VQZJyUbLAsCB/jYlBI+ucRivizNgQlurNKhDs5EvK6Kt7W2e9qD5fWod3eIOwFueQckwg0hX6gUXlaxvh93HcMOfMEc1GG8OP5THPnBB2FG4nnY/7zt80lWQsfrlnPr7n50X+tk9euDsTVfSSy+spQ/QS8wk0ZWiV+l0Y6i2zOnZlgh+4nAL5U+aacg1+aWeQ,iv:HuljmTPfGs7qyuk6MnNwImmkaEBvUmhN+o2LUjw5W/M=,tag:QdcQ43VF4fSAC2SP58v0pw==,type:str]
        client-key-data: ENC[AES256_GCM,data:OoeGrkmMaiD0bUeckwR1yh4TA7n7T7yyelFJ1DzYFNkMWwmbD4L/67bUsSd9RjDINL96hx3CEORsEZNbGp2cdgP9rYZEHVXr6X8SJVAjLOVTCEUz2iEvaX0xM5v8WWr5XGuzRVujVVA44q6RqvxuoNEuqQmtWEYWX6w3DSsdAgQJlL+caFEnCmHNNhLD+jUuEq7aWmkocOc8FQzD8uBqMA==,iv:Xx+FcYPzzgInVlCZ5dvRmMblyunoIpeqXZ7gaW7TDvI=,tag:vCZLWSZNIHXqlTvqLODrqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1442vmk8fl5nxrejuj0g6a63cqdw7q7ufvnxuqf3wcsnetgmv2phsl8eufu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaXdiTkFTVS9PNmhIVTJq
            b3V3VlJLNTBxWmtPaVpjS096aXhxa0pKTHo0Ckc4SUFnWmhvSkRFVjdHUWV0Qm10
            Q04ydjVjWmhxeXc5ZEZmdjVhb1lBRVkKLS0tIDFxempBcnMvamxvVmw5NzlTSDh5
            NExxcGVYTUd6Ri9aMTkvdnJSNGtqdUEKImnJKvL/E4XbLNgiSnWJ11xel38gFw19
            jjyIFVBotyWHiZ1lYj60/0uG0xoUottUqbjH/yg9Bn/cDzqrpDonpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-22T12:14:04Z"
    mac: ENC[AES256_GCM,data:myvAUMm+niZ6G3rNs9Jc2l/OxZDd9v3xrko4gUNOtftROEsbPdlYnXpvBlbP2zwxbyEoGsaMDcZMK4kT1AlM90NPoJ+kWtHBCxviIAuxZ4rmoo/v6t/eNNQ0xgfR0X/ViaN/dTOhASjdBW7jGj591bJO86NfJ/KULxfdwCDbxHI=,iv:IpLwmYalTELHi1wOEnxMfBM6+fCdSTfoBafqopk64zE=,tag:NeVtPajahLJBdRSgaC3Gqg==,type:str]
    pgp:
        - created_at: "2024-03-13T13:45:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA3FtoE4fF3lxAQ//fFOjwTt8fbxBVVBqEgkuHlpjolQWrdmQvck/on16CU6J
            t8IWHMSv4759+4wkLT2NagPWe4EewXv4x1v7K7PXtLCYtLwxvnq6mclt6aJHloVc
            EfbwgsO97/OOz1JVXL/TMGo1eymPdicZZW9epjzKjONmAiPZiMK0wlGQeissLgiJ
            uQXDDPiR7mu2FvHBcQIOwqfkF6djdL5CCKijpavR6Bytjd4KDYYMdfvqlIVl9M6d
            3tBeiaRTZKh3LVrFflyHfODT+uwS78O7x5RU6ZrAFFX/0LisDDj1vH43E15Xrpjj
            PN0yoPvcF+Nzw5aPn5JI/KYDolG/PQarj1uwTVSNPyqdfLiXlUBDA5AWwTzwFVDW
            mVmIwLouzbOSG/5mv8VHd3hXiE+qvYxducX90GLdbBP4m+ddFuw/qrPGr5NoHJKI
            KZr1sSVLGXF1vjvztmJTUL1hSEkn3zRLTTIsYNe/ucJBG4CtD2U9APRUxK96NYdO
            YqdynBvck1Y3ogzIDvtJwAVQ0P6RSDbwXjKwr/HEU0ACoVH06I36ZFwehSLZ29wB
            2FZ8WyknPyvY5gg3/C1ZaBju3o30mWzmQDxXMPRqYxfl9DqlVZxvBgWFaw5bSSFZ
            FU+gNkLH/biX3p2dT9DGWOH2/NLVYF9UNDS8aL268QFLdPY7C6dJKhcso1efNaPS
            XgFhjtU3urgDg3QM6K953jwEhW5MEp+nAASPR0NTAWnbozeQL5E8Xz7pa9AcK+tb
            ec+DY3G6CnlCbtHhsNxl9Wc3zMeVwqDG9AD0zVTPp6jXY8nQbVA8oSbTnB3SfPY=
            =uM0Q
            -----END PGP MESSAGE-----
          fp: DC8231FEA934DB14D402E72D3B6555ADB3910EAE
        - created_at: "2024-03-13T13:45:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMAzD2NYmhq+4pAQwAmCXFnrgz/zRd4MSqN5dFUnY5lTM2bgcnXLg4fU3buhj0
            IT/CLnaYOaWRQ0b9Uf85gpYOp+xSXKqFbLOxOVoLBj0GNfE9ZtoarwNwXTx7a99b
            tf2/dTG4JtiJ+rVVYJMC9YsMrIkAZfiLMAxT4lurgsk+rZdWc9kQ0ilEXxdxbKRr
            pevCCPRfjO1b22PpnT4IVZCbT6F5ft83KpcTkkRrmSpOgGJmaOiBQ4ob11pvM2Ww
            H/0ejv1PseW4XWlJLLLsOMO3xeoQVNKze8fDiQYp/LBVBGYokJlFYuEkbwL7/bKE
            FlGWu1IIMeRiVP5LJQP7geY3aLt7+vIw6bNpXWXlwKn5plc4Ri2YWwhAo8g+E5f8
            vR8bT7g4OQyU567FEWL7mVsDnHuWurGm5NxUXMCVwku/nCufCZgRCYVEbFLzbo1R
            clL/bCaGGJh7FTnA7mWseGlGQKRXUl1/X4asqBL5m9Kq9CXgHG3f/x6zrvcLVS/r
            FivgtcmHOiqm6MMBGAXy0l4BFp3JaSf4pGcJPp3e6M23G4aLA+thzzQHH0143urd
            eW5FE+QY8vmoTkmnALoF5IfUc6ztDDMBoNdsbLjBMwplQqRrQDXKewnqljEi/7ay
            2G97L7VWirjJTNSKXHBl
            =ll0s
            -----END PGP MESSAGE-----
          fp: 74CCFCF1D43B0DB742CC2602A103D9F46B9D2E02
        - created_at: "2024-03-13T13:45:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D5jdJleHfCY0SAQdAFBKHY30Sf6sH0CMQIXYV0sro9Gi2LxYQmIdIbG77B0Mw
            grEFrI7bPKaufDPFMLQPsOSWP2ySzo8vjtzdPyUfdhr0gTm3okdLjv/YXPuPVsPY
            0l4B7sUaP3y2eyU1jsZPNhpQwp+fDck5PdFl7GdWly2DlkNYSi/YSVODJSz9gYDi
            iwLxaeYNJhayTUicNj065wwMoAi8HY5Mug+OC2MyA/CESOvnHrWoJorwLTSwrcH1
            =2eMN
            -----END PGP MESSAGE-----
          fp: CC7B10CE8D78010ABB043F8DB1C462E90012ECFE
        - created_at: "2024-03-13T13:45:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DWYQsjg0n8MQSAQdAkEicP8hV3SQPl3UizuULpUVG76lceINxBdtWAbQRkUsw
            H+bokx+rNIz7bGCC0LS+71Bdessj3+ZUT7JIhOVS0DOg0opUI2ykkGCGUN1WfBmq
            0l4Bm/Gn8qqgKNMX04jsBQ6TQ8SlzOIRz2yx7qrgqHKzwkng4qbGoeE2o/ZFsJpV
            yayV5Da4BNqqJbJ1CHvsggkvxrLsww6vq8gHJO5oai5BD/1cU/dFQaH7xEGFuaE8
            =zj1d
            -----END PGP MESSAGE-----
          fp: 22E1B5B742AA7D66DB7FA859E5DB947DBEA3A7F4
    unencrypted_suffix: _unencrypted
    version: 3.8.1
