apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "fairagro-onlyoffice.jwt_secret" . }}"
  labels:
    {{- include "fairagro-onlyoffice.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret: "{{ .Values.jwt_secret }}"
