postgres_db:
  size: 10Gi
  storageClass: ~

gitlab:
  certmanager:
    install: false

  # unfortunately we cannot deactivate the certmanager-issuer
  # certmanager-issuer:
  #   email: dummy@zalf.de # won't be used but required by chart

  postgresql:
    install: false

  nginx-ingress:
    enabled: false

  nginx-ingress-geo:
    enabled: false

  prometheus:
    install: false

  upgradeCheck:
    enabled: false # Workaround. Otherwise gitlab won't install.

  global:
    time_zone: Europe/Berlin
    edition: ce

    hosts:
      domain: fairagro.net
      hostSuffix: test
      https: true

    ingress:
      configureCertmanager: false
      useNewIngressForCerts: false
      provider: nginx
      class: nginx-external
      tls:
        enabled: true
        secretName: gitlab-tls-dummy-secret
      annotations:
        cert-manager.io/issuer: geant
        cert-manager.io/private-key-size: "4096"
        cert-manager.io/private-key-rotation-policy: "Always"
        # It seems the subjects annotation do not have any effect.
        # Still we keep them...
        cert-manager.io/subject-countries: "DE"
        cert-manager.io/subject-organizations: "NFDI FAIRagro"
        cert-manager.io/subject-organizationalunits: "Measure 4.1"
      enabled: true
      path: /
      pathType: Prefix

    psql:
      password:
        secret: gitlab.fairagro-postgresql-gitlab.credentials.postgresql.acid.zalan.do
        key: password
      host: fairagro-postgresql-gitlab
      port: 5432
      username: gitlab
      database: gitlab

  gitlab:
    webservices:
      ingress:
        tls:
          enabled: true
          secretName: gitlab-webservices-tls-secret
          # annotations:
          #   nginx.ingress.kubernetes.io/service-upstream: "true"
          #   cert-manager.io/issuer: geant
          #   cert-manager.io/private-key-size: "4096"
          #   cert-manager.io/private-key-rotation-policy: "Always"
          #   # It seems the subjects annotation do not have any effect.
          #   # Still we keep them...
          #   cert-manager.io/subject-countries: "DE"
          #   cert-manager.io/subject-organizations: "NFDI FAIRagro"
          #   cert-manager.io/subject-organizationalunits: "Measure 4.1"

  registry:
    ingress:
      tls:
        enabled: true
        secretName: gitlab-registry-tls-secret
        # annotations:
        #   nginx.ingress.kubernetes.io/service-upstream: "true"
        #   cert-manager.io/issuer: geant
        #   cert-manager.io/private-key-size: "4096"
        #   cert-manager.io/private-key-rotation-policy: "Always"
        #   # It seems the subjects annotation do not have any effect.
        #   # Still we keep them...
        #   cert-manager.io/subject-countries: "DE"
        #   cert-manager.io/subject-organizations: "NFDI FAIRagro"
        #   cert-manager.io/subject-organizationalunits: "Measure 4.1"

  minio:
    ingress:
      tls:
        enabled: true
        secretName: gitlab-minio-tls-secret
        # annotations:
        #   nginx.ingress.kubernetes.io/service-upstream: "true"
        #   cert-manager.io/issuer: geant
        #   cert-manager.io/private-key-size: "4096"
        #   cert-manager.io/private-key-rotation-policy: "Always"
        #   # It seems the subjects annotation do not have any effect.
        #   # Still we keep them...
        #   cert-manager.io/subject-countries: "DE"
        #   cert-manager.io/subject-organizations: "NFDI FAIRagro"
        #   cert-manager.io/subject-organizationalunits: "Measure 4.1"
