apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-additional-config
data:
  proxy.config.php: |
    <?php
    $CONFIG = array (
      'trusted_proxies' => array(
        0 => '127.0.0.1',
        1 => '{{ .Values.allowed_reverse_proxy_ips }}',
      ),
      'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
    );
  trusted_domains.config.php: |
    <?php
    $CONFIG = array (
      'trusted_domains' => array(
        0 => 'nextcloud-test.fairagro.net',
{{- $idx := 1 | int -}}
{{- if .Values.nextcloud_internal_ingress.fqdn }}
        {{ $idx }} => '{{ .Values.nextcloud_internal_ingress.fqdn }}',
{{- $idx = add1 $idx -}}
{{- end }}
{{- if .Values.nextcloud_external_ingress.fqdn }}
        {{ $idx }} => '{{ .Values.nextcloud_external_ingress.fqdn }}',
{{- end }}
      ),
    );