apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-additional-config
data:
  proxy.config.php: |
    <?php
    $CONFIG = array (
      'trusted_proxies' => array(
        0 => '127.0.0.1',
        1 => '{{ .Values.allowed_reverse_proxy_ips }}',
      ),
      'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
    );
  redis-session.ini: |
    session.save_handler = redis
    session.save_path = "tcp://{{ template "nextcloud.redis.fullname" }}:{{ .Values.nextcloud.redis.master.service.ports.redis | default 6379 | quote }}?auth={{ .Values.nextcloud.redis.auth.password }}"
    redis.session.locking_enabled = 1
    redis.session.lock_retries = -1
    redis.session.lock_wait_time = 10000
