apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: fairagro-nextcloud-backup-daily
  namespace: velero
spec:
  schedule: 0 7 * * *
  template:
    includedNamespaces:
      - "{{ .Release.Namespace }}"
    includedResources:
      - "*"
    includeClusterResources: true
    storageLocation: default
    ttl: 192h0m0s # 8 days
    hooks:
      resources:
        - name: nextcloud-maintenance
          includedNamespaces:
            - "{{ .Release.Namespace }}"
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: nextcloud
              app.kubernetes.io/component: app
          pre:
            - exec:
                container: nextcloud
                command:
                  - /bin/sh
                  - -c
                  - /usr/local/bin/php /var/www/html/occ maintenance:mode --on
                onError: Fail
                timeout: 10s
          post:
            - exec:
                container: nextcloud
                command:
                  - /bin/sh
                  - -c
                  - /usr/local/bin/php /var/www/html/occ maintenance:mode --off
                onError: Fail
                timeout: 10s
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: fairagro-nextcloud-backup-weekly
  namespace: velero
spec:
  schedule: 0 6 * * 1
  template:
    includedNamespaces:
      - "fairagro-nextcloud"
    includedResources:
      - "*"
    includeClusterResources: true
    storageLocation: default
    ttl: 840h0m0s # 5 weeks
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: fairagro-nextcloud-backup-monthly
  namespace: velero
spec:
  schedule: 0 5 1 * *
  template:
    includedNamespaces:
      - "fairagro-nextcloud"
    includedResources:
      - "*"
    includeClusterResources: true
    storageLocation: default
    ttl: 9480h0m0s # 13 months
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: fairagro-nextcloud-backup-yearly
  namespace: velero
spec:
  schedule: 0 4 1 1 *
  template:
    includedNamespaces:
      - "fairagro-nextcloud"
    includedResources:
      - "*"
    includeClusterResources: true
    storageLocation: default
    ttl: 87600h0m0s # 10 years
