apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: fairagro-nextcloud-backup-manually
  namespace: velero
spec:
  # this schedule will never run
  schedule: "0 0 31 2 ?" # this is non-standard cron syntax with seconds as firt part
  skipImmediately: true
  template:
    includeClusterResources: true
    includedNamespaces:
      - fairagro-nextcloud
    includedResources:
      - "*"
    storageLocation: default
    ttl: 87600h0m0s
    hooks:
      resources:
        - name: backup-postgresql-master
          includedNamespaces:
            - fairagro-nextcloud
          labelSelector:
            matchLabels:
              application: spilo
              spilo-role: master
          pre:
            - exec:
              container: postgres
              command:
                - "/usr/bin/bash"
                - "-c"
                - "su -l postgres -c 'envdir /run/etc/wal-e.d/env /scripts/postgres_backup.sh /home/postgres/pgdata/pgroot/data'"
