apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-installation-scripts
data:
  pre-installation.sh: |
    #!/bin/sh

    # change permissions of nextcloud data directory so nextcloud does not complain
    chmod -R 0770 {{ .Values.nextcloud.nextcloud.datadir }}
  post-installation.sh: |
    #!/bin/sh

    # install NextcloudOffice plugin
    php /var/www/html/occ app:install richdocuments

    # Set allowed CollaboraOffice hosts to talk to nextcloud
    php /var/www/html/occ config:app:set richdocuments wopi_allowlist --value={{ .Values.allowed_collabora_ips }}

    # add missing database indices
    php /var/www/html/occ db:add-missing-indices
