apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-installation-scripts
data:
  wait-for-postgresql.php: |
    #!/usr/bin/env php

    <?php
    // Database connection string
    $dsn = "pgsql:host=" . $_ENV['POSTGRES_HOST'] . ";dbname=" . $_ENV['POSTGRES_DB'] . ";user=" . $_ENV['POSTGRES_USER'] . ";password=" . $_ENV['POSTGRES_PASSWORD'];
    // Maximum number of connection attempts
    $max_attempts = 300;

    $attempt = 1;
    $connected = false;
    // Wait until the database is ready
    while (!$connected && $attempt <= $max_attempts) {
      try {
        $pdo = new PDO($dsn);
        $connected = true;
        echo "Successfully connected to the postgresql database";
      } catch (PDOException $e) {
        sleep(1);
        $attempt++;
      }
    }

    if (!$connected) {
      echo "Failure to connect to the postgresql database";
      exit(1);
    }
    ?>
  post-installation.sh: |
    #!/bin/sh

    # install NextcloudOffice plugin
    php /var/www/html/occ app:install richdocuments

    # Set allowed CollaboraOffice hosts to talk to nextcloud
    {{ $collabora_server := (index .Values "collabora-online").collabora.server_name }}
    php /var/www/html/occ config:app:set richdocuments wopi_url --value=https://{{ $collabora_server }}:443
    php /var/www/html/occ config:app:set richdocuments wopi_allowlist --value={{ .Values.allowed_collabora_ips }}

    # add missing database indices
    php /var/www/html/occ db:add-missing-indices
