apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-installation-scripts
data:
  wait-for-postgresql.sh: |
    #!/usr/bin/env sh

    php_code=$(cat <<'EOF'
    // Database connection string
    $dsn = "pgsql:host=" . $_ENV['POSTGRES_HOST'] . ";dbname=" . $_ENV['POSTGRES_DB'] . ";user=" . $_ENV['POSTGRES_USER'] . ";password=" . $_ENV['POSTGRES_PASSWORD'];
    // Maximum number of connection attempts
    $max_attempts = 900;

    $attempt = 1;
    $connected = false;
    // Wait until the database is ready
    while (!$connected && $attempt <= $max_attempts) {
      try {
        $pdo = new PDO($dsn);
        $connected = true;
        echo "Successfully connected to the postgresql database";
      } catch (PDOException $e) {
        sleep(1);
        $attempt++;
      }
    }

    if (!$connected) {
      echo "Failure to connect to the postgresql database";
      exit(1);
    }
    EOF
    )

    php -r "$php_code"
  post-installation.sh: |
    #!/usr/bin/env sh

    {{- $collabora_enabled := (index .Values "collabora-online").enabled }}
    {{- $onlyoffice_enabled := (index .Values "fairagro-onlyoffice").enabled }}

    {{- if and $collabora_enabled (not $onlyoffice_enabled) }}
    # install Nextcloud Office plugin
    php /var/www/html/occ app:install richdocuments

    # Set allowed CollaboraOffice hosts to talk to nextcloud
    {{- $collabora_server := (index .Values "collabora-online").collabora.server_name }}
    php /var/www/html/occ config:app:set richdocuments wopi_url --value=https://{{ $collabora_server }}:443
    php /var/www/html/occ config:app:set richdocuments wopi_allowlist --value={{ join "," .Values.allowed_collabora_ips }}
    {{- end }}

    {{- if and $onlyoffice_enabled (not $collabora_enabled) }}
    # install OnlyOffice integration (using richdocuments and enabling WOPI for OnlyOffice would also be possible)
    php /var/www/html/occ app:install onlyoffice

    # Configure OnlyOffice integration app
    {{- $onlyoffice_server := (first (index .Values "fairagro-onlyoffice").ingress.hosts).host }}
    {{- $nextcloud_server := .Values.nextcloud.nextcloud.host }}
    {{- $jwt_secret := (index .Values "fairagro-onlyoffice").jwt_secret }}
    php /var/www/html/occ config:app:set onlyoffice DocumentServerUrl --value=https://{{ $onlyoffice_server }}/
    # For some reason we also we to set the (internal) StorageURL which is the nextcloud URL.
    php /var/www/html/occ config:app:set onlyoffice StorageUrl --value=https://{{ $nextcloud_server }}/
    php /var/www/html/occ config:app:set onlyoffice jwt_secret --value={{ $jwt_secret }}
    # Enable manual save
    php /var/www/html/occ config:app:set onlyoffice customizationForcesave --value=true
    {{- end }}

    # Install additional apps
    # needed to forbid WebDAV access with Windows Explorer -- additional manual settings are required
    php /var/www/html/occ app:install files_accesscontrol
    php /var/www/html/occ app:install calendar
    php /var/www/html/occ app:install deck
    php /var/www/html/occ app:install announcementcenter

    # Disable unwanted apps
    php /var/www/html/occ app:disable admin_audit
    php /var/www/html/occ app:disable bruteforcesettings
    php /var/www/html/occ app:disable encryption
    php /var/www/html/occ app:disable files_external
    php /var/www/html/occ app:disable firstrunwizard
    php /var/www/html/occ app:disable support
    php /var/www/html/occ app:disable survey_client
    php /var/www/html/occ app:disable suspicious_login
    php /var/www/html/occ app:disable twofactor_totp
    php /var/www/html/occ app:disable user_ldap
    php /var/www/html/occ app:disable user_status
    php /var/www/html/occ app:disable weather_status

    # add missing database indices
    php /var/www/html/occ db:add-missing-indices
