apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-post-installation-scripts
data:
  post-installtion.sh: |-
    #!/bin/sh

    # install NextcloudOffice plugin
    su -s /bin/sh www-data -c "php /var/www/html/occ app:install richdocuments"

    # Set allowed CollaboraOffice hosts to talk to nextcloud
    {{- $collabora_host := (index .Values "collabora-online").collabora.server_name }}
    su -s /bin/sh www-data -c "php /var/www/html/occ config:app:set richdocuments wopi_allowlist --value={{ $collabora_host }}"

    # add missing database indices
    su -s /bin/sh www-data -c "php /var/www/html/occ db:add-missing-indices"
