apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextcloud-backup-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: velero-backup-creator
  namespace: velero
rules:
  - apiGroups: ["velero.io"]
    resources: ["backups"]
    verbs: ["get", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nextcloud-backup-role
rules:
  - apiGroups: [""] # core API group
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create"]
  - apiGroups: ["apps"] # apps API group
    resources: ["deployments"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fairagro-nextcloud-velero-backup-creator-binding
  namespace: velero
subjects:
  - kind: ServiceAccount
    name: nextcloud-backup-account
    namespace: nextcloud
roleRef:
  kind: Role
  name: velero-backup-creator
  apiGroup: rbac.authorization.k8s.io
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nextcloud-backup-rolebinding
subjects:
  - kind: ServiceAccount
    name: nextcloud-backup-account
    namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: Role
  name: nextcloud-backup-role
  apiGroup: rbac.authorization.k8s.io
