kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nextcloud-backup
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nextcloud-backup
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: nextcloud-backup
  apiGroup: rbac.authorization.k8s.io
