apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextcloud-backup-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: velero-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
      - namespaces
    verbs:
      - "*"
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - list
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - "customresourcedefinitions"
    verbs:
      - get
  - apiGroups: ["velero.io"]
    # resources: ["backups"]
    # verbs: ["get", "create"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nextcloud-backup-role
rules:
  - apiGroups: [""] # core API group
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create"]
  - apiGroups: ["apps"] # apps API group
    resources: ["deployments"]
    verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nextcloud-backup-rolebinding
subjects:
  - kind: ServiceAccount
    name: nextcloud-backup-account
roleRef:
  kind: Role
  name: nextcloud-backup-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fairagro-nextcloud-velero-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: velero-clusterrole
subjects:
  - kind: ServiceAccount
    name: nextcloud-backup-account
    namespace: "{{ .Release.Namespace }}"
