{{- with .Values.nextcloud_internal_ingress }}
{{ if and .crt .key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-tls-secret-internal
type: kubernetes.io/tls
stringData:
  # You can include additional key value pairs as you do with Opaque Secrets
  tls.crt: |
    {{- .crt | nindent 4 }}
  tls.key: |
    {{- .key | nindent 4 }}
{{- end }}
{{- end }}
# {{- with .Values.nextcloud_external_ingress }}
# {{ if and .crt .key }}
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: nextcloud-tls-secret-external
# type: kubernetes.io/tls
# stringData:
#   # You can include additional key value pairs as you do with Opaque Secrets
#   tls.crt: |
#     {{- .crt | nindent 4 }}
#   tls.key: |
#     {{- .key | nindent 4 }}
# {{- end }}
# {{- end }}
{{- range (get .Values "collabora-online").ingress.tls }}
{{ if .secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName }}
type: kubernetes.io/tls
stringData:
  # You can include additional key value pairs as you do with Opaque Secrets
  tls.crt: {{- $.Values.collabora_tls.crt | toYaml | indent 2 }}
  tls.key: {{- $.Values.collabora_tls.key | toYaml | indent 2 }}
{{- end }}
{{- end }}
