# Default values for keycloak.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: keycloak-helm.corki.bonares.de
      paths:
        - path: /
          pathType: Prefix
  tls:
   - hosts:
       - keycloak-helm.corki.bonares.de

resources:
  limits:
    cpu: 2.0
    memory: 2Gi
  requests:
    cpu: 1.0
    memory: 1Gi

keycloak:
  adminUser: admin
  adminPassword: admin

database:
  type: postgres
  host: keycloak.paas-brachland.draven.cluster.zalf.de
  port: 30493
  username: keycloak
  password: SUXmIOiiEF2pVewJ5SGtoof6dkomdFlwtkvekxtMZOYQ7OtB24tSAfp7CnvKPmL2
