apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ coalesce .Values.service.targetPort .Values.service.port }}
      protocol: TCP
      name: keycloak-svc
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
