apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fairagro-datahub.fullname" . }}
  labels:
    {{- include "fairagro-datahub.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fairagro-datahub.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fairagro-datahub.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fairagro-datahub.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "fairagro-datahub.imagename" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                external_url 'https://{{ include "fairagro-datahub.fqdn" . }}';
                nginx['listen_port'] = {{ .Values.service.port }};
                nginx['listen_https'] = false;
                nginx['proxy_protocol'] = true;
                nginx['real_ip_trusted_addresses'] = ['127.0.0.0/8', '172.16.0.0/16'];
                nginx['real_ip_header'] = 'X-Forwarded-For';
                nginx['real_ip_recursive'] = 'on'
# nginx['enable'] = false;
# puma['listen'] = '0.0.0.0';
# puma['port'] = {{ .Values.service.port }};
# gitlab_rails['trusted_proxies'] = ['172.16.0.0/16']
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: gitlab-config
              mountPath: /etc/gitlab
            - name: gitlab-logs
              mountPath: /var/log/gitlab
            - name: gitlab-data
              mountPath: /var/opt/gitlab
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: gitlab-config
          persistentVolumeClaim:
            claimName: pvc-fairagro-datahub-config
        - name: gitlab-logs
          persistentVolumeClaim:
            claimName: pvc-fairagro-datahub-logs
        - name: gitlab-data
          persistentVolumeClaim:
            claimName: pvc-fairagro-datahub-data
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
