{{- if not (and .Values.tls.key .Values.tls.crt) }}
apiVersion: v1
kind: Secret
metadata:
  name: geant-acme-account-secret
type: Opaque
stringData:
  secret: "{{ .Values.geant_acme_hmac_key }}"
{{- end }}