{{- if not (and .Values.tls.key .Values.tls.crt) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: geant
spec:
  acme:
    # The ACME server URL
    server: https://acme.sectigo.com/v2/OV
    # Email address used for ACME registration
    email: "{{ .Values.cert_email_receiver }}"
    externalAccountBinding:
      keyID: "{{ .Values.geant_acme_key_id }}"
      keySecretRef:
        name: geant-acme-account-secret
        key: secret
      keyAlgorithm: HS256
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: cert-issuer-geant
    # Enable the DNS-01 challenge provider
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
{{- end }}