apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fairagro-basic-middleware.fullname" . }}
  labels:
    {{- include "fairagro-basic-middleware.labels" . | nindent 4 }}
data:
  config.yml: |
{{ .Values.middlewareConfig | indent 4 }}